#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Ejecutar ESLint
npm run lint
if [ $? -ne 0 ]; then
    echo "ESLint failed. Please fix the issues before committing."
    exit 1
fi

# Ejecutar pruebas
npm test
if [ $? -ne 0 ]; then
    echo "Tests failed. Please fix the issues before committing."
    exit 1
fi
